### ISSUE TITLE
Update README: clarify where tsconfig.json should go to share with editor

### ISSUE THREAD

**Issue by Ubehebe** [bazelbuild/rules_typescript#144]
VSCode and other IDEs expect to find a file named `tsconfig.json` at the root of your TypeScript project. By contrast, `ts_library` allows each target to specify its own `tsconfig.json`, and the passed-in file is processed by Bazel to add things like node module mappings, so that the actual compiler invocation works.

This means that opening a Bazel-managed project in VSCode, even one that has a single handwritten `tsconfig.json`, is not a great experience. There are red squigglies pointing to node modules and other dependencies outside the source tree.

What is the intended workflow here? Symlinking the Bazel-processed `tsconfig.json` into the source tree root might work, but maybe you have a different idea.

**Comment by yohcop** [comment]
I don't think you want to use the bazel generated tsconfig.json with your editor, the import paths are going to be strange.

I have a tsconfig.json that works, outside of bazel, that I reuse with bazel. Bazel will just override things in it, like import paths. But it doesn't matter as long as your tsconfig works outside of Bazel.

Of course VSCode, or other editors, probably can't deal with per-file or per-library tsconfigs, but one works just fine.

One thing I had to do, was to add the workspace name as an alias, to make absolute imports work.

**Comment by alexeagle** [comment]
1) like @yohcop says, you should just author a tsconfig.json file in the root directory of your sources (like maybe a sibling of WORKSPACE, or possibly in a nested `src/` directory or something) that governs the type-checking in the editor, and put whatever you need in that file to make the editor happy. Then point bazel there. Will update the readme to be more clear.

2) We recommend a single tsconfig.json file for the whole repository, since all it governs is the opt-in strictness settings of the compiler. Anything that needs to vary from package to package is managed for you by Bazel.

3) You'll be interested in some existing issues (could use community contributions!)

- In a sufficiently large project, this approach is broken because you can't open the entire project in an editor without running out of memory. In that case maybe Bazel *should* generate something you symlink into your source tree (That in fact is what we do internally at Google to solve this) -
 https://github.com/bazelbuild/rules_typescript/issues/53
- We should warn you when your tsconfig.json settings are overridden by Bazel: https://github.com/bazelbuild/rules_typescript/issues/34

(Note for me: should close https://github.com/bazelbuild/rules_typescript/issues/47 along with this, by doing a pass over the documentation)

**Comment by kellycampbell** [comment]
Is there a way to suppress the warnings from #34? We have several options set for our editor (e.g. vscode) so the warning is just extra noise on every build. Or perhaps it could only warn if the file's settings differ from what bazel will use?

**Comment by alexeagle** [comment]
to close the loop here - as @kellycampbell points out those warnings were annoying and not actionable; we later removed them.
