### ISSUE TITLE
`require('./file.json')` or __dirname work as expected in JavaScript but not TypeScript

### ISSUE THREAD

**Issue by hansl** [bazelbuild/rules_typescript#154]
I have a minimal reproduction here: https://github.com/hansl/bazel-rules-typescript-data-repro

The JavaScript test works, while the TypeScript test doesn't.

**Comment by alexeagle** [comment]
Yeah this is a bug, it's right here:
https://github.com/bazelbuild/rules_nodejs/blob/0162fdbe8ed986c9b5d5b79e53c98385ddaf6edd/internal/node/node_loader.js#L236

we call the original require implementation, passing along the parent, but we've already resolved to a list of possible absolute paths to load from, so it will never look like a relative import, and we lose the parent.

**Comment by alexeagle** [comment]
Okay I spent some more time on this one.
The bug isn't what I said earlier - we don't need to teach multi-root module resolution. We expect that at runtime the files are next to each other again because the multiple root dirs are flattened in the runfiles (at least for tests and binaries - for things running in the toolchain maybe the execroot will matter)

All we need to do to fix this is turn on `--preserve-symlinks` option to node. However this breaks the world and will be hard to roll out - it exposes non-hermeticity such as https://github.com/angular/angular/blob/master/BUILD.bazel#L22 which is missing all the transitive depnedencies.

**Comment by hansl** [comment]
Yes, that was my understanding as well (that symlinks were resolved to paths that didn't include the JSON file required, while the original source was used in JavaScript).

How is Jasmine not hermeticity-friendly, btw?

Nota; not preserving symlinks in the JavaScript rules also lead to non-hermeticity.

**Comment by alexeagle** [comment]
sorry, what I mean by that angular example is: we list jasmine but not its transitive dependency jasmine-core, which illustrates that actions depending on this filegroup for inputs must be non-hermetic if they are working.

I think we need to roll out https://github.com/bazelbuild/rules_nodejs/commit/49055902200a55bdb48759caba0936add033b99b again, with a plan to fix

**Comment by alexeagle** [comment]
`--preserve-symlinks` is rolled out as the default, so I think this is fixed (don't have time to verify, pls re-open if I'm wrong)
