### ISSUE TITLE
npm install doesn't work on windows

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#16]
because the `npm` binary lives in the root of the package, not under a `bin` directory like the linux package.
/cc @ocombe

**Comment by ocombe** [comment]
Yes, it's just that the files are packaged differently between OSX and Windows: https://github.com/bazelbuild/rules_typescript/blob/master/internal/node_install.bzl#L59
Moving "npm", "npm.cmd" and "node.exe" in a "bin" folder for the bazel windows binary would probably be better than fixing your script (so that's it's the same between all OS binaries)

**Comment by alexeagle** [comment]
Sorry for lack of update - I have a partial fix for this but it's blocked on our internal Jenkins CI getting an updated bazel release that doesn't run process-wrapper on Windows.

**Comment by alexeagle** [comment]
`bazel run @yarn//:yarn` works on windows now.
`bazel run @nodejs//:npm` is broken, now tracked at https://github.com/bazelbuild/rules_nodejs/issues/21
