### ISSUE TITLE
Default tsconfig for ts_library should include `lib: es2015`

### ISSUE THREAD

**Issue by jelbourn** [bazelbuild/rules_typescript#170]
At this point es2015 features are widely supported and should be the default.

**Comment by alexeagle** [comment]
Note, we've had a long-standing issue to do this within google as well, /cc @evmar 
Ideally we should make this change for both bazel and blaze users around the same time, if nothing else it's  less context switching and ensures we take the same approach for both.

Main blocker I know of is that some teams ship to a platform like a TV with an old browser - but these teams are already in trouble because they might depend on a third-party lib with a JS distribution, and there's no type-checker to ensure they don't link non-conforming code into their app. So the right solution is some static analysis downstream of the TS compilation.

**Comment by alexeagle** [comment]
I think this is obsolete - all the ts_library settings should be up to the user, and Bazel's defaults should be the same as TypeScript's defaults.
