### ISSUE TITLE
nodejs_binary depending on ts_library should get higher-level syntax

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_typescript#216]
Devs should have a way to configure ts_library 's JS target.

When `ts_library` is being used for Nodejs applications the target is a bit different than browser applications.
For a browser app you always want to use es5 since you don't know what browser your app is going to be run on. 
But with Nodejs you can pick the Nodejs version and therefore know ahead of time what target it supports.
Therefore by picking a higher target you can often gain performance from your application, depending on use case.

Another reason for allowing variable targets is interpoerablity with other nodejs modules. One such example of not supporting es5 is the popular ORM Sequelize https://github.com/RobinBuschmann/sequelize-typescript/blob/master/lib/models/BaseSequelize.ts#L14

**Comment by alexeagle** [comment]
Currently we have exactly two output flavors from TypeScript rules, and @mprobst has pushed back when we suggested adding more (Angular has a need for "ESM5" which we have a hacky way to produce in 
https://github.com/angular/angular/blob/master/packages/bazel/src/esm5.bzl

I'd rather avoid the complexity of having more output flavors. If we can keep nodejs programs using the "devmode" (non-optimizer/bundler friendly) output, this keeps our system simpler.

The simple resolution to this issue seems to be raising the `--target` of devmode compilations to `es2015`, we just need to confirm we don't break users who rely on ES5 syntax in the browser for whatever reason.

(Note, the devmode output is not intended to ship to end-user browser runtime, so there's no constraint there)

**Comment by alexeagle** [comment]
es2015 devmode is now the default, it applies to nodejs inputs too

**Comment by thesayyn** [comment]
It is awkward that why I can't use a different module and target value in my tsconfig since I'm not depending on ts_devserver. the current options prevent me from enabling resolveJsonModule because it requires a commonjs & es2015 target.  Maybe we can add an option to let the advanced user fly freely.

**Comment by marcus-sa** [comment]
^ I agree.
I've gone back and thought about moving completely over to Bazel, since you can't even define the target for TypeScript...

**Comment by Toxicable** [comment]
You can specify an override the default target with `devmodeTargetOverride` in your tsconfig
```
  "bazelOptions": {
    "devmodeTargetOverride": "esnext"
  },
```
Also note that at runtime we use the `devmode` artifacts, which default to es2015 for nodejs, `prodmode` artifacts are used for web bundling targets.

**Comment by alexeagle** [comment]
I'm thinking increasingly that ts_library should produce the constrained output formats when consumed by the provider, but the default output should just be the JS you asked for using the --target/--module you specify

**Comment by thesayyn** [comment]
Also you can use googmodule option if you want commonjs modules instead of umd.

**Comment by thesayyn** [comment]
@alexeagle is it possible to use commonjs modules with es6_module_mappings? I mean it will target commonjs modules and at the same time we will continue to use goodness of module_name?  If it possible I can work on that

**Comment by alexeagle** [comment]
I don't see why we would support both our custom module mapping and commonjs. Either you're using our opinionated output because of its interop with downstream rules (UMDs are fine for node) or in the proposal above you would opt-out by writing whatever strange outputs from ts_library you like but then you can't expect anything downstream of that to understand what you did.

**Comment by DavidANeil** [comment]
https://github.com/bazelbuild/rules_nodejs/issues/122#issuecomment-368102668
> I guess I'm not sure why the ts_library rule needs to change the tsconfig at all. It seems a lot simpler to me to just let the person writing the code to also write the config.

Updating rules_typescript/rules_nodejs/rules_angular is a constant struggle for us as we have to maintain patches that disable these tsconfig overrides and give us the output we asked for in our `tsconfig.json`, and no output that we didn't ask for.  It would be nice to do what you suggested @alexeagle and also to get rid of this split dev/prod mode and config overriding.
I am not super experienced with aspects, but it seems like it would be possible to add something like an es5_aspect and es6_aspect that consumers can then apply as needed if they want multiple versions of output.  Or maybe providers is the correct way.
I think there are probably many solutions that let people have multiple outputs without forcing everyone to have both.

If we (@JaredNeil or I) can help make this a reality we'd be glad to help.
