### ISSUE TITLE
Add support for generating goog modules

### ISSUE THREAD

**Issue by JaredNeil** [bazelbuild/rules_typescript#230]
Currently the [`tsc_wrapped/compiler_host.ts`](https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/compiler_host.ts) reads the [`googmodule` property](https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/compiler_host.ts#L113) from the tsconfig, but it isn't ever set in [tsconfig.bzl](https://github.com/bazelbuild/rules_typescript/blob/master/internal/common/tsconfig.bzl#L122).

In my testing, setting it to `true` causes the [`ngc_wrapped/index.ts`](https://github.com/angular/bazel-builds/blob/master/src/ngc-wrapped/index.ts) compiler to output goog modules, because it uses the `tsc_wrapped/compiler_host.ts` and [emits with tsickle](https://github.com/angular/bazel-builds/blob/master/src/ngc-wrapped/index.ts#L260), but I haven't been able to get [`tsc_wrapped.ts`](https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/tsc_wrapped.ts) to emit goog modules directly because it appears to use [some other emit](https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/tsc_wrapped.ts#L145).

**Comment by alexeagle** [comment]
Here's what I'm currently thinking:
https://github.com/bazelbuild/rules_typescript/compare/master...alexeagle:googmodule

I'm proposing a different rule than `ts_library`, with the intent that `ts_goog_library` would actually live in your repository and not be part of the public API of rules_typescript.
That's because there's no runtime interop story between the named UMD modules produced currently and the goog.module emit that closure library understands. So it would be unsupported to have a mix of `ts_library` and `ts_goog_library` targets in the same build graph.

You might run into trouble using any third-party libraries, but I'm sure you already had to shim those for closure compiler anyway.

what do you think?

**Comment by JaredNeil** [comment]
Yeah, that might work.
Why can't this be a thing that is decided by the downstream rule like `target` and `module` are?
It already decides between ES5/AMD and ES6/ESM, so seems like adding ESx/goog fits in well with that paradigm.

**Comment by alexeagle** [comment]
That would be nicer, but it means we'd need to have three provided flavors rather than two, and our code isn't well-factored to have many provided flavors (lots of places we just have a boolean check for is_es6 essentially)
Also it makes it easy that you build `:some_top_level_target` and end up building every `.ts` input N times because you make use of all the flavors somewhere.

Every now and then I argue over this with @mprobst and maybe we could do enough refactoring to support more output flavors. Ideally nodejs wouldn't use the same browser devmode outputs either.

I think this is the way to get you unblocked for now, assuming that you never need the ES5/AMD flavor and can just override it.

**Comment by JaredNeil** [comment]
Yeah, that seems reasonable.

**Comment by alexeagle** [comment]
@mprobst that's a great idea, I can easily output goog.module's with
`bazel build :some_ts_library --define=module=goog`
The problem is that the define is global, which means we'll also compile `tsc_wrapped` with goog module syntax, so running it would require a patched nodejs that understands how to translate that at runtime back to commonjs.
Maybe that's a possibility for LucidChart though.
