### ISSUE TITLE
What's up with the recent renaming of the workspaces?

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/rules_typescript#422]
I am trying to upgrade to 0.25. Everything was fine (despite minor hiccups)  until I found that the workspace names are changed as of https://github.com/bazelbuild/rules_typescript/pull/412.

I have tried to find more information about this renaming. I am very interested in learning the rationale behind such a change. It seems, ..., mysterious at the moment to me.

**Comment by alexeagle** [comment]
Sorry, we ought to have made the conversation about this public. We are now using a generic method for any npm package to ship bazel rules, including third parties. We don't want to namespace all the rules in this first-party way (with bazel.build in the name) because it makes it harder for an ecosystem of third-party rules to grow up.

For example we just introduced an `@bazel/jasmine` package in https://github.com/bazelbuild/rules_nodejs/pull/543 - the name for this is better namespaced according to where the user gets it from (`npm_bazel_jasmine`) rather than where it's developed (`build_bazel_rules_nodejs_packages_jasmine`) or a fictitious URL like `build_bazel_rules_jasmine') which implies that github.com/bazelbuild/rules_jasmine would exist.

We need to do cleanups like this before we declare a 1.0 and stop being experimental.

**Comment by qzmfranklin** [comment]
Thanks for the update. I think I have figured out how everything works by now - a bit late, but better than never. Even though this is a breaking change, I like it for a few reasons. Thanks.
