### ISSUE TITLE
Absolute path imports

### ISSUE THREAD

**Issue by codesuki** [bazelbuild/rules_typescript#65]
I had some problems with absolute imports. 
Example: `import A from 'proto/A';`

My project layout is like this
```
/
/WORKSPACE
/BUILD.bazel
/app/
/app/BUILD.bazel
/app/proto
...
/app/index.ts
```

So to make it work, in `index.ts`, I have to import `app/proto/A`. 
Is there any way to be able to just import from `proto/A` ?

**Comment by alexeagle** [comment]
I am surprised that importing from `app/proto/A` works. That is not intended. You could easily have a top-level directory whose name collides with an installed npm package, so it would be ambiguous.

There are two options:
1) "workspace absolute imports", which will be in the next release (see #77). `import A from 'my_workspace/app/proto/A'`. This is okay because bazel assumes your workspace name is globally unique (and for JS purposes, you could use your npm package name as the workspace name like we do in tsickle)
2) Give a local name to a package. See this example: https://github.com/bazelbuild/rules_typescript/blob/master/examples/some_module/BUILD.bazel#L27
We name the module "some-lib" and so we can import from there in another package: https://github.com/bazelbuild/rules_typescript/blob/master/examples/bar.ts#L21

**Comment by codesuki** [comment]
I was surprised, too. When I compile manually with typescript I have my `baseDir` in `/app`, thats why I used to import relative to `baseDir` like `import 'proto/...'`.

If setting my own `baseDir` is not possible then `1.` looks like a nice way to do it with bazel. All imports will have to be changed to include the workspace but that's not a problem.

Looking forward to the next release! Although more than this import problem I hope https://github.com/bazelbuild/rules_typescript/pull/76 gets merged :)
