### ISSUE TITLE
Upgrade to protobufjs 6

### ISSUE THREAD

**Issue by calebegg** [bazelbuild/rules_typescript#71]
I spent quite a while tracing through an issue with protobufjs that stems from the fact that I had manually installed it, meaning it was at the latest version, 6, and tsc_wrapped apparently fails if it's on 6 instead of 5, in a way that seems...incredibly opaque to me. tsc_wrapped isn't even in the stack trace below(!!), but I did eventually track it down to that, and downgrading to 5 fixed the issue.

I unfortunately can't think of a way that would make this easier for past-Caleb to debug, but upgrading to protobufjs 6 would solve the specific problem regardless.

(As an aside, I find this all pretty weird that NPM/Yarn wouldn't yell at me about having incompatible versions being depended on, or just install both versions for the appropriate project. Otherwise, what's the point of semver and including versions at all? Maybe this is some basic thing that I just haven't experienced, but it seems crazy to me.)

```
$ bazel build src
INFO: Found 1 target...
ERROR: /Users/calebegg/Code/mta/src/BUILD.bazel:4:1: Compiling TypeScript (devmode) //src:src failed (Exit 1).
failed to load main  TypeError: Cannot read property 'resolve' of undefined
    at Object.<anonymous> (/Users/calebegg/Code/mta/node_modules/protobufjs/src/root.js:62:39)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/calebegg/Code/mta/node_modules/protobufjs/src/index-light.js:83:29)
    at Module._compile (module.js:570:32)
Target //src:src failed to build
```

**Comment by alexeagle** [comment]
NPM/Yarn probably installed both protobufjs versions in node_modules.
The challenge is, which version does a given `require` load? The semantics depend on the calling script. If the calling script in `node_modules/@bazel/typescript` has its own `node_modules/@bazel/typescript/node_modules/protobufjs` then it should use that one.

I suspect your issue is due to our own Bazel-ified module loading patch, see https://github.com/bazelbuild/rules_nodejs/commit/ebbad65504cd0a0007987b6adce3b77a8a898ee8
this is needed because we support `require('some-name')` where `some-name` is the `module_name` of a build rule in the dependencies, not installed by npm/yarn. (effectively we have our own private npm repository inside bazel). That commit actually broke module loading in a different case.

I need to understand these scenarios better and include coverage for them in the rules_nodejs repo so that module loading always follows the npm semantics, yet also supports our internal loading. (Of course we don't have an example to follow in google3 because we don't use npm semantics)

**Comment by calebegg** [comment]
Aha, interesting. I'm not sure I've ever encountered node_modules/foo/node_modules structures. There's a lot I still don't know about npm....

**Comment by hoodie** [comment]
@alexeagle I've run into a similar issue where `rules_typescript` uses pbjs5 but our own code uses pbjs6 and both where in the same resolution path. I'm not grasping the entire setup yet, but doesn't this look like an isolation issue? I reordered the [`resolveLocations`](https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node_loader.js#L112) in `rules_nodejs/internal/node_loader.js` and suddenly tsc_wrapped_bin used the correct version. please check this out, looks like a bug.

**Comment by kellycampbell** [comment]
I'm also running into this problem. It looks like the wrapped tsc should only be using the _tsc_wrapped_deps node_modules, but it's using both those and the project's node_modules.

Note that I'm not using the @bazel/typescript package, but am referencing this github from my WORKSPACE. I have the following protobufjs packages:

```
$ find  -L . -name protobufjs
./node_modules/protobufjs
./bazel-myproject/external/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/protobufjs
./bazel-myproject/node_modules/protobufjs
./bazel-myproject/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped_bin.runfiles/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/protobufjs
./bazel-myproject/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped_bin.runfiles/myproject/external/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/protobufjs
./bazel-myproject/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc.runfiles/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/protobufjs
./bazel-myproject/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc.runfiles/myproject/external/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/protobufjs
./bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped_bin.runfiles/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/protobufjs
./bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped_bin.runfiles/myproject/external/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/protobufjs
./bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc.runfiles/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/protobufjs
./bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc.runfiles/myproject/external/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/protobufjs
```

**Comment by mprobst** [comment]
FYI I've looked into this a bit for unrelated reasons, and I believe #188 is not sufficient to make rules_typescript compatible with protobufjs 6.

It turns out v6 is a complete rewrite of protobufjs (see https://github.com/dcodeIO/protobuf.js/issues/485) (yay!). Notable changes for us are that there are no more getter & setter functions, messages are no longer constructor, and ByteBuffer is no longer used. This means all code in `worker.ts` that accesses protos needs to change, but also the message reading loop logic.

I'm still puzzling a bit on how to pull this off. The change to `worker.ts` while non-trivial is not that complex. The bigger problem is that v6 is incompatible and has lots of very non-obvious semantic changes (plus very little checking on top of it). This means to land it, we'd need to update a lot of Google-internal code.

**Comment by alexeagle** [comment]
I think the root cause here was that we mixed the dependencies of tsc_wrapped with those the user installed.
Ever since switching to an npm-delivered package `@bazel/typescript`, we can have whatever version of protobuf.js in our dependencies without regard for a different version used by the users code.
So this is obsolete.
